name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep "_FUNC"
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          CONTAINS_BUG_FUNC: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'o') }}
