name: Conditions workflow
on: push
jobs:
  skip-or-run:
    if: ${{ github.actor == 'octocat' }} # job単位で実行をスキップ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
  step2:
    if: ${{ github.actor == 'ekozmdev' }} # job単位で実行をスキップ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ekozmdev"