name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '3') }} # ワークフロー実行IDに1が含まれていればこのstepが実行される
      - run: echo ${{ github.run_id }}
      