name: Contexts
on: push
jobs:
  print-contexts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}" # jobの確認画面のstep一覧の時点で展開されているっぽい
      - run: echo "${GITHUB_ACTOR}" # github.actorと同じ情報が入っているstep一覧の時点で展開されていない
      - run: echo "${{ github.run_id }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.repository_owner }}"
      # - run: echo "${{ github.actor.event.pull_request.title }}"
      - run: echo "${{ runner.name }}"
      - run: echo "${{ runner.os }}"
      - run: echo "${{ runner.arch }}"
      - run: echo "${{ runner.temp }}"
      - run: echo "${{ runner.tool_cache }}"
      - run: echo "${{ runner.debug }}"

