name: Environment variables
on: push
jobs:
  run-1:
    runs-on: ubuntu-latest
    env:
      BRANCH: main # jobレベルの環境変数
    steps:
      - run: echo "${BRANCH}" # Linuxの環境変数の参照の仕方
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }} # Github Actionsのコンテクストの参照の仕方
  run-2:
    runs-on: ubuntu-latest
    env:
      BRANCH: test # jobレベルの環境変数
    steps:
      - run: echo "${BRANCH}" # Linuxの環境変数の参照の仕方
