name: Environment variables
on: push
jobs:
  run:
    runs_on: ubuntu-latest
    env:
      BRANCH: main # jobレベルの環境変数
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
