name: Secrets
on: push
jobs:
  print-secrets:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${PASSWORD}" # マスクされる
      - run: echo "S:uperSecret!"
      - run: echo "${PASSWORD:0:1}" # マスクされない
      - run: echo "${PASSWORD#?}" # マスクされない
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" # マスクされない